name: Proselint and WriteGood Check

on:
  pull_request:
    branches: [ master ]

jobs:
  proselint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python environment
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install proselint write-good

      - name: Run Proselint and WriteGood checks
        run: |
          proselint ./**/*.md $(find . -name '*.md' -not -path ".github/*") || echo "Proselint errors found!"
          write-good ./**/*.md $(find . -name '*.md' -not -path ".github/*") || echo "WriteGood suggestions found!"

      - name: Fail workflow if errors or suggestions found
        if: ${{ always() }}
        run: |
          if [[ ${PROSELINT_EXIT_CODE} -ne 0 || ${WRITE_GOOD_EXIT_CODE} -ne 0 ]]; then
            exit 1
          fi

